name: expense_tracker
description: expense-tracker

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  charts_flutter: ^0.12.0
  flutter_svg: ^1.0.3
  flutter:
    sdk: flutter
  get: ^4.3.8
  cupertino_icons: ^1.0.2
  multi_circular_slider: ^1.0.0
  percent_indicator: ^4.0.1
  persistent_bottom_nav_bar: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/png/
    - assets/images/svg/
    - assets/images/bottom_navigation/
    



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Urbanist
      fonts:        
        - asset: fonts/Urbanist-VariableFont_wght.ttf
        # - asset: fonts/Urbanist-Regular.ttf
        # - asset: fonts/Urbanist-Medium.ttf
        # - asset: fonts/Urbanist-SemiBold.ttf
        # - asset: fonts/Urbanist-Bold.ttf
        # - asset: fonts/Urbanist-ExtraBold.ttf
        # - asset: fonts/Urbanist-Black.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
